-- Table , 시퀀스 등 구조 정의
-- DROP SEQUENCE SQ_DEPT;
-- CREATE SEQUENCE SQ_DEPT START WITH 50 INCREMENT BY 10;

-- DROP SEQUENCE SQ_EMP;
-- CREATE SEQUENCE SQ_EMP START WITH 8000 INCREMENT BY 1;

DROP SEQUENCE SQ_FAQ;
CREATE SEQUENCE SQ_FAQ START WITH 1 INCREMENT BY 1;

-- DROP SEQUENCE SQ_CUSTOMER;
-- CREATE SEQUENCE SQ_CUSTOMER START WITH 1 INCREMENT BY 1;

DROP SEQUENCE SQ_QNA;
CREATE SEQUENCE SQ_QNA START WITH 1 INCREMENT BY 1;

DROP SEQUENCE SQ_FILE;
CREATE SEQUENCE SQ_FILE START WITH 1 INCREMENT BY 1;

-- GALLERY -> PROPERTY
DROP SEQUENCE SQ_PROPERTY;
CREATE SEQUENCE SQ_PROPERTY START WITH 1 INCREMENT BY 1;

-- DROP SEQUENCE SQ_TUTORIAL;
-- CREATE SEQUENCE SQ_TUTORIAL START WITH 1 INCREMENT BY 1;

-- 추가(기존 테이블 삭제하고 다시 만들기)
-- DROP SEQUENCE SQ_RESERVATION;
-- CREATE SEQUENCE SQ_RESERVATION START WITH 1 INCREMENT BY 1;

-- DROP TABLE TB_EMP CASCADE CONSTRAINT;
-- DROP TABLE TB_DEPT CASCADE CONSTRAINT;
DROP TABLE TB_FAQ CASCADE CONSTRAINT;
-- DROP TABLE TB_CUSTOMER CASCADE CONSTRAINT;
DROP TABLE TB_QNA CASCADE CONSTRAINT;

DROP TABLE TB_FILE CASCADE CONSTRAINT;
DROP TABLE TB_PROPERTY CASCADE CONSTRAINT;
-- DROP TABLE TB_TUTORIAL CASCADE CONSTRAINT;

-- 추가(기존 테이블 삭제하고 다시 만들기)
-- DROP TABLE TB_RESERVATION CASCADE CONSTRAINT;



CREATE TABLE TB_FAQ
(
    NO          NUMBER NOT NULL PRIMARY KEY,
    TITLE       VARCHAR2(255),
    CONTENT     VARCHAR2(255),
    DELETE_YN   VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME VARCHAR2(255),
    UPDATE_TIME VARCHAR2(255),
    DELETE_TIME VARCHAR2(255)
);

-- CREATE TABLE TB_CUSTOMER
-- (
--     CID         NUMBER NOT NULL PRIMARY KEY,
--     FIRST_NAME  VARCHAR2(255),
--     LAST_NAME   VARCHAR2(255),
--     EMAIL       VARCHAR2(255),
--     PHONE       VARCHAR2(255),
--     DELETE_YN   VARCHAR2(1) DEFAULT 'N',
--     INSERT_TIME VARCHAR2(255),
--     UPDATE_TIME VARCHAR2(255),
--     DELETE_TIME VARCHAR2(255)
-- );

-- 11/22 수정
CREATE TABLE TB_QNA
(
    QNO         NUMBER NOT NULL PRIMARY KEY,
    SUBJECT     VARCHAR2(255),
    NAME        VARCHAR2(255),
    MESSAGE     VARCHAR2(255),
    EMAIL       VARCHAR2(255),
    DELETE_YN   VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME VARCHAR2(255),
    UPDATE_TIME VARCHAR2(255),
    DELETE_TIME VARCHAR2(255)
);

-- Upload Table
CREATE TABLE TB_FILE
(
    FID          NUMBER NOT NULL PRIMARY KEY,
    FILE_TITLE   VARCHAR2(1000),
    FILE_CONTENT VARCHAR2(1000),
    FILE_NAME    VARCHAR2(1000),
    FILE_TYPE    VARCHAR2(1000),
    FILE_DATA    BLOB,
    DELETE_YN    VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME  VARCHAR2(255),
    UPDATE_TIME  VARCHAR2(255),
    DELETE_TIME  VARCHAR2(255)
);

-- Upload TB_PROPERTY (11/22 추가)
CREATE TABLE TB_PROPERTY
(
    PNO                   NUMBER NOT NULL PRIMARY KEY,
    PROPERTY_TITLE        VARCHAR2(1000),   -- 제목
    PROPERTY_FILE_NAME    VARCHAR2(1000),   -- 사진파일 이름
    PROPERTY_TYPE         VARCHAR2(1000),   -- 파일 타입(업로드시 자동입력_jpg 등)
    PROPERTY_DATA         BLOB,         -- 파일속성(업로드시 자동입력)
    PROPERTY_PRICE        VARCHAR2(1000),   -- 매물가격
    PROPERTY_ADDRESS      VARCHAR2(1000),   -- 세부주소
    PROPERTY_CITY         VARCHAR2(1000),   -- 도시, 국가
    PROPERTY_BED          NUMBER,       -- 방 갯수
    PROPERTY_BATH         NUMBER,       -- 화장실 갯수
    DELETE_YN             VARCHAR2(1) DEFAULT 'N',
    INSERT_TIME           VARCHAR2(255),
    UPDATE_TIME           VARCHAR2(255),
    DELETE_TIME           VARCHAR2(255)
);

-- Upload TB_TUTORIAL Excel Table
-- CREATE TABLE TB_TUTORIAL
-- (
--     ID                   NUMBER NOT NULL PRIMARY KEY,
--     TITLE                VARCHAR2(1000),
--     DESCRIPTION          VARCHAR2(1000),
--     PUBLISHED            VARCHAR2(1000),
--     DELETE_YN            VARCHAR2(1) DEFAULT 'N',
--     INSERT_TIME          VARCHAR2(255),
--     UPDATE_TIME          VARCHAR2(255),
--     DELETE_TIME          VARCHAR2(255)
-- );

-- 예약 테이블(11/21_ 여행 사이트 백엔 연동)
-- CREATE TABLE TB_RESERVATION
-- (
--     RID                  NUMBER NOT NULL PRIMARY KEY,
--     EMAIL                VARCHAR2(1000),
--     FIRST_NAME           VARCHAR2(1000),
--     LAST_NAME            VARCHAR2(1000),
--     SIGHTS               VARCHAR2(1000),    -- 관광지
--     START_DATE           VARCHAR2(1000),    -- 시작날짜
--     END_DATE             VARCHAR2(1000),    -- 종료날짜
--     RESERVATION_YN       VARCHAR2(1) DEFAULT 'Y',   -- 예약가능여부
--     ADDRESS              VARCHAR2(1000),    -- 주소
--     PHONE                VARCHAR2(1000),    -- 전화번호
--     DELETE_YN            VARCHAR2(1) DEFAULT 'N',
--     INSERT_TIME          VARCHAR2(255),
--     UPDATE_TIME          VARCHAR2(255),
--     DELETE_TIME          VARCHAR2(255)
-- );